# Generated by Django 5.0.4 on 2024-04-29 19:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Proveedor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100, unique=True)),
                ("apellido", models.CharField(max_length=100)),
                ("dni", models.CharField(max_length=8)),
                ("telefono", models.CharField(max_length=15)),
                ("cuit", models.CharField(max_length=11)),
                ("direccion", models.CharField(max_length=100)),
                ("email", models.EmailField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="Producto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=200)),
                (
                    "categoria",
                    models.CharField(
                        choices=[
                            ("hogar", "Hogar - Muebles"),
                            ("deporte", "Deporte y fitness"),
                            ("salud", "Salud"),
                            ("moda", "Moda"),
                            ("electrodomesticos", "Electródomesticos"),
                            ("herramientas", "Herramientas"),
                            ("belleza", "Belleza y cuidado personal"),
                        ],
                        max_length=17,
                    ),
                ),
                ("stock_actual", models.PositiveIntegerField()),
                ("precio", models.FloatField(verbose_name="Precio")),
                (
                    "alta_del_producto",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Alta del producto"
                    ),
                ),
                (
                    "fecha_de_modificacion",
                    models.DateTimeField(auto_now=True, verbose_name="Se modifico"),
                ),
                (
                    "proveedor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="compra.proveedor",
                        verbose_name="Proveedor",
                    ),
                ),
            ],
        ),
    ]
